### ISSUE TITLE
random crash on Android 8.0.0

### ISSUE THREAD

**Issue by githubber2222** [JakeWharton/ProcessPhoenix#32] opened 2019-05-19 13:31 UTC
This crash happened now for first time, app is rolled out in play store and never any issue so pretty sure not a configuration issue.

Device: Galaxy A5(2017) running Android 8.0.0

Anyone ever seen this?

Stacktrace
```java
Fatal Exception: java.lang.IllegalStateException: Unable to determine default activity for com.xxx. Does an activity specify the DEFAULT category in its intent filter?
       at com.jakewharton.processphoenix.ProcessPhoenix.getRestartIntent(ProcessPhoenix.java:89)
       at com.jakewharton.processphoenix.ProcessPhoenix.triggerRebirth(ProcessPhoenix.java:55)
       at com.xxx.MainApplication.restartApp(MainApplication.java:486)
```

Intent filter
```xml
<intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
    <category android:name="android.intent.category.MULTIWINDOW_LAUNCHER" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

**Comment by githubber2222** [comment] 2019-05-19 14:26
forgot to mention: using V2.0.0

**Comment by lazercorn** [comment] 2019-05-30 01:26
Try using 
`implementation 'com.jakewharton:process-phoenix:2.0.1-SNAPSHOT'`

See if that works

**Comment by henriquenfaria** [comment] 2019-10-24 09:25
maybe check [this](https://github.com/JakeWharton/ProcessPhoenix/issues/31)

**Comment by JakeWharton** [comment] 2021-06-25 20:04
Yep, dupe of linked issue. Fix is integrated and will be released soon.

**Closed by JakeWharton** 2021-06-25 20:04 UTC
